Repository laitsky/mxm21-oprec-client, pull requests merged in 2021-02, with the labels that each got.

#11 Responsive/1.0.0 a.2
  package-lock.json
  package.json
  src/shared/styles/buttons.ts
  src/shared/styles/containers.ts
  src/views/oprec/DataDiri/DataDiri.tsx
  src/views/oprec/EsaiSingkat/EsaiSingkat.tsx
  src/views/oprec/FinalOprec/FinalOprec.tsx
  src/views/oprec/FinalisasiData/FinalisasiData.tsx
  src/views/oprec/FinalisasiData/constants.ts
Labels: refactoring

#13 Daftar divisi/1.0.0 a.2
  src/assets/logo-divisi/acara.png
  src/assets/logo-divisi/bazaar.png
  src/assets/logo-divisi/dekorasi.png
  src/assets/logo-divisi/dokumentasi.png
  src/assets/logo-divisi/fm.png
  src/assets/logo-divisi/index.ts
  src/assets/logo-divisi/medrel.png
  src/assets/logo-divisi/merchandise.png
  src/assets/logo-divisi/perkap.png
  src/assets/logo-divisi/publikasi.png
  src/assets/logo-divisi/seccom.png
  src/assets/logo-divisi/sponsor.png
  src/assets/logo-divisi/visual.png
  src/assets/logo-divisi/website.png
  src/services/oprec.service.ts
  src/shared/styles/cards.ts
  src/shared/styles/containers.ts
  src/types/index.ts
  src/views/oprec/DaftarDivisi/DaftarDivisi.tsx
  src/views/oprec/DaftarDivisi/constants.ts
Labels: enhancement

#14 ui/ux koor auth OK
  public/index.html
  src/shared/constants/index.ts
  src/shared/constants/styles.ts
  src/shared/motions/MxmLoading/MxmLoading.tsx
  src/shared/motions/MxmLoading/helpers.ts
  src/shared/motions/MxmLoading/index.ts
  src/shared/styles/buttons.ts
  src/shared/styles/cards.ts
  src/shared/styles/header.ts
  src/shared/styles/keyframes.ts
  src/views/auth/Login/Login.tsx
  src/views/auth/NewPassword/NewPassword.tsx
  src/views/auth/Register/Register.tsx
  src/views/oprec/FinalisasiData/FinalisasiData.tsx
  src/views/oprec/SelamatDatang/SelamatDatang.tsx
Labels: enhancement

#15 1.0.0 a.2
  package-lock.json
  package.json
  public/index.html
  src/assets/logo-divisi/acara.png
  src/assets/logo-divisi/bazaar.png
  src/assets/logo-divisi/dekorasi.png
  src/assets/logo-divisi/dokumentasi.png
  src/assets/logo-divisi/fm.png
  src/assets/logo-divisi/index.ts
  src/assets/logo-divisi/medrel.png
  src/assets/logo-divisi/merchandise.png
  src/assets/logo-divisi/perkap.png
  src/assets/logo-divisi/publikasi.png
  src/assets/logo-divisi/seccom.png
  src/assets/logo-divisi/sponsor.png
  src/assets/logo-divisi/visual.png
  src/assets/logo-divisi/website.png
  src/services/oprec.service.ts
  src/shared/constants/index.ts
  src/shared/constants/styles.ts
  src/shared/motions/MxmLoading/MxmLoading.tsx
  src/shared/motions/MxmLoading/helpers.ts
  src/shared/motions/MxmLoading/index.ts
  src/shared/styles/buttons.ts
  src/shared/styles/cards.ts
  src/shared/styles/containers.ts
  src/shared/styles/header.ts
  src/shared/styles/keyframes.ts
  src/types/index.ts
  src/views/auth/Login/Login.tsx
  src/views/auth/NewPassword/NewPassword.tsx
  src/views/auth/Register/Register.tsx
  src/views/oprec/DaftarDivisi/DaftarDivisi.tsx
  src/views/oprec/DaftarDivisi/constants.ts
  src/views/oprec/DataDiri/DataDiri.tsx
  src/views/oprec/EsaiSingkat/EsaiSingkat.tsx
  src/views/oprec/FinalOprec/FinalOprec.tsx
  src/views/oprec/FinalisasiData/FinalisasiData.tsx
  src/views/oprec/FinalisasiData/constants.ts
  src/views/oprec/SelamatDatang/SelamatDatang.tsx
Labels: bug, enhancement, refactoring
